onlineclasswebpage/urls.py
from django.contrib import admin
from django.urls import path
from django.views.generic import RedirectView
from django.conf.urls import include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('webpage/', include('webpage.urls')),
    path('', RedirectView.as_view(url='/webpage/')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
    + static(settings.IMAGE_URL, document_root=settings.IMAGE_ROOT)

urlpatterns += [
    # path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('allauth.urls')),
]

webpage/urls.py
from django.urls import path
from . import views
from django.conf.urls import url
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
  path('', views.home_page, name='home-page'),
  path('admin-post-create', views.AdminPostCreate.as_view(), name='admin-post-create'),
  path('<int:pk>/post-delete', views.post_delete, name='post-delete'),
  path('<int:pk>/update', views.post_update, name='post-update'),

  path('course-specialists', views.CourseSpecialistListView.as_view(), name='course-specialist-list'),
  path('course-specialist-create', views.course_specialist_create, name='course-specialist-create'),
  path('course-specialists/<int:pk>/update', views.course_specialist_update, name='course-specialist-update'),
  path('course-specialists/<int:pk>/delete', views.course_specialist_delete, name='course-specialist-delete'),
  path('<int:pk>/course-specialist-detail', views.CourseSpecialistDetail.as_view(), name='course-specialist-detail'),

  path('courses', views.CourseListView.as_view(), name='course-list'),
  path('course-create', views.course_create, name='course-create'),
  path('<int:pk>/course-detail', views.CourseDetail.as_view(), name='course-detail'),
  path('courses/<int:pk>/update', views.course_update, name='course-update'),
  path('courses/<int:pk>/delete', views.course_delete, name='course-delete'),

  path('create-account', views.create_account, name='create-account'),
  path('register/<int:pk>', views.RegisterStudentCreate.as_view(), name='register-with-course'),
  path('register', views.RegisterStudentCreate.as_view(), name='register'),

  path('<int:pk>/course-post-list', views.course_post_list, name='course-post-list'),
  path('course/<int:pk>/specialist-post-create', views.specialist_post_create, name='specialist-post-create'),

  path('course/<int:pk>/course-question-create', views.course_question_create, name='course-question-create'),
  path('course/<int:course_id>/question/<int:qus_id>/delete', views.question_delete, name='qus-delete'),
  path('course/<int:course_id>/question/<int:qus_id>/answer', views.question_answer, name='qus-answer'),
  path('student/<int:student_id>/course/<int:course_id>/delete', views.course_delete_by_student, name='course-delete-by-student'),
]

webpage/models.py
from django.db import models
from datetime import date
from django.contrib.auth.models import User
from django.urls import reverse
import datetime

from django.contrib.auth.models import AbstractUser
from django.utils.translation import gettext_lazy as _

class CourseSpecialist(models.Model):
  """ course specialist """
  name = models.OneToOneField(User, on_delete=models.SET_NULL, null=True, verbose_name="course specialist")
  photo = models.ImageField(upload_to='images/', default='defo')
  bio = models.TextField(max_length=1000, help_text="Enter your bio details here.")
  
  class Meta:
    ordering = ["name", "bio"]

  def get_absolute_url(self):
    pass

  def __str__(self):
    return self.name.username

class Course(models.Model):
  """ Course """
  name = models.CharField(max_length=200, unique=True)
  course_specialist = models.ForeignKey(CourseSpecialist, on_delete=models.SET_NULL, null=True)
  photo = models.ImageField(upload_to='images/', default='defo')
  duration = models.IntegerField()
  limit_student = models.IntegerField()
  payment = models.IntegerField()
  description = models.TextField(max_length=1000)
  
  class Meta:
    ordering = ["name"]

  def get_absolute_url(self):
    pass

  def __str__(self):
    return self.name

class Post(models.Model):
  """ Post """
  content = models.TextField(max_length=1000)
  photo = models.ImageField(upload_to='images/', default='defo')
  course = models.ForeignKey(Course, verbose_name='course', on_delete=models.CASCADE)
  post_creator = models.ForeignKey(CourseSpecialist, on_delete=models.CASCADE)
  post_date = models.DateTimeField(default=datetime.datetime.now)
  
  class Meta:
    ordering = ["post_date"]

  def get_absolute_url(self):
    pass

  def __str__(self):
    return self.content

class RegisterStudent(models.Model):
  """ register student """
  name = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
  course = models.ForeignKey(Course, verbose_name='course', on_delete=models.CASCADE)
  start_date = models.DateTimeField(default=datetime.datetime.now)
  
  class Meta:
    ordering = ["start_date"]
    unique_together = (('name', 'course'),)

  def get_absolute_url(self):
    pass

  def __str__(self):
    return self.name.username

class CourseQuestion(models.Model):
  """ Course Question """
  student = models.ForeignKey(RegisterStudent, verbose_name='student', on_delete=models.SET_NULL, null=True)
  course = models.ForeignKey(Course, verbose_name='course', on_delete=models.CASCADE)
  question = models.TextField(max_length=1000)
  is_answered = models.BooleanField(default=False)
  start_date = models.DateTimeField(default=datetime.datetime.now)
  
  class Meta:
    ordering = ["start_date"]

  def get_absolute_url(self):
    pass

  def __str__(self):
    return self.question

webpage/forms.py
import datetime
from django import forms
from django.forms import ModelForm, ValidationError
from webpage.models import Post, CourseSpecialist, Course, RegisterStudent, User, CourseQuestion

class AdminPostForm(forms.Form):
  content = forms.CharField(widget=forms.Textarea, help_text="Enter content for post")
  photo = forms.ImageField(help_text="Choose photo")

  def clean_content(self):
    content_data = self.cleaned_data['content']
    return content_data

  def clean_photo(self):
    photo_data = self.cleaned_data['photo']
    return photo_data

class PostForm(forms.ModelForm):
  class Meta:
    model = Post
    fields = ['content', 'photo']

class CourseSpecialistForm(forms.ModelForm):
  class Meta:
    model = CourseSpecialist
    fields = ['name', 'photo', 'bio']

class CourseForm(forms.ModelForm):
  class Meta:
    model = Course
    fields = ['name', 'course_specialist', 'photo', 'duration', 'limit_student', 'payment', 'description']

class UserForm(forms.Form):
  username = forms.CharField(help_text="Enter your name")
  email = forms.CharField(help_text="Enter your email")
  password = forms.CharField(widget=forms.PasswordInput, help_text="Enter ypur password")

  def clean_username(self):
    username_data = self.cleaned_data['username']
    if User.objects.filter(username=username_data).exists():
      raise forms.ValidationError(u'Username "%s" already exists.' % username_data)
    return username_data

  def clean_email(self):
    email_data = self.cleaned_data['email']
    return email_data

  def clean_password(self):
    password_data = self.cleaned_data['password']
    return password_data

class CourseQuestionForm(forms.Form):
  question = forms.CharField(widget=forms.Textarea, help_text="Enter your question")

  def clean_content(self):
    content_data = self.cleaned_data['question']
    return content_data

webpage/views.py
from django.shortcuts import render, redirect
from django.views import generic
from .models import CourseSpecialist, Course, Post, RegisterStudent, User, CourseQuestion
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import CreateView, DeleteView
from webpage.forms import PostForm, CourseSpecialistForm, CourseForm, UserForm, CourseQuestionForm, AdminPostForm
from django.urls import reverse
from django.shortcuts import get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
import datetime

def home_page(request):
    if request.user.is_authenticated:
      co_specialist = CourseSpecialist.objects.filter(name=request.user).count()
      if co_specialist == 1:
        course_specialist = CourseSpecialist.objects.get(name=request.user)
        context = {
          'course_specialist': course_specialist,
        }
      else:
        students = RegisterStudent.objects.filter(name=request.user)
        context = {
          'students': students,
        }
    else:
      user_id, created = User.objects.get_or_create(is_superuser=1)
      course_specialist = CourseSpecialist.objects.get(name=user_id)
      # except MyModel.DoesNotExist:
      #   raise Http404("No MyModel matches the given query.")
      context = {
        'course_specialist': course_specialist,
      }

    return render(request, 'webpage/home_page.html', context=context)

# admin post create
# def admin_post_create(request):
#   if request.method == 'POST':
#     form = AdminPostForm(request.POST, request.FILES)
#     if form.is_valid():
#       admin_post = Post()
#       admin_post.content = form.cleaned_data['content']
#       admin_post.photo = form.cleaned_data['photo']
#       admin_post.save()

#       return HttpResponseRedirect(reverse('home-page'))

#   else:
#     form = AdminPostForm()

#   context = {
#     'form': form,
#   }

#   return render(request, 'webpage/adminpost_form.html', context)

class AdminPostCreate(LoginRequiredMixin, CreateView):
  model = Post
  fields = ['content', 'photo', 'course', 'post_creator', 'post_date']

  def get_initial(self):
    initial = super().get_initial()
    post_creator = CourseSpecialist.objects.get(name=self.request.user)
    initial['post_creator'] = post_creator
    return initial
  success_url = reverse_lazy('home-page')

# admin post delete
def post_delete(request, pk):
  query = Post.objects.get(pk=pk)
  query.delete()
  if query.course == None:
    return HttpResponseRedirect(reverse('home-page'))
  else:
    return HttpResponseRedirect(reverse('course-post-list', kwargs={'pk': query.course.id}))

# admin post update
def post_update(request, pk): 
  instance = get_object_or_404(Post, pk=pk)
  form = PostForm(request.POST or None, instance=instance)
  if form.is_valid():
    form.save()
    post = Post.objects.get(pk=pk)
    if post.course == None:
      return HttpResponseRedirect(reverse('home-page'))
    else:
      return HttpResponseRedirect(reverse('course-post-list', kwargs={'pk': post.course.id}))
  return render(request, 'webpage/post_form.html', {'form': form}) 

# course specialist list
class CourseSpecialistListView(generic.ListView):
  model = CourseSpecialist

# course_specialist_create
def course_specialist_create(request):
  if request.method == 'POST':
    form = CourseSpecialistForm(request.POST, request.FILES)
    if form.is_valid():
      form.save()

      return HttpResponseRedirect(reverse('course-specialist-list'))

  else:
    form = CourseSpecialistForm()

  context = {
    'form': form,
  }

  return render(request, 'webpage/coursespecialist_form.html', context)

# course_create
def course_create(request):
  if request.method == 'POST':
    form = CourseForm(request.POST, request.FILES)
    if form.is_valid():
      form.save()

      return HttpResponseRedirect(reverse('course-list'))

  else:
    form = CourseForm()

  context = {
    'form': form,
  }

  return render(request, 'webpage/course_form.html', context)

# update course specialist
def course_specialist_update(request, pk): 
  instance = get_object_or_404(CourseSpecialist, pk=pk)
  form = CourseSpecialistForm(request.POST or None, instance=instance)
  if form.is_valid():
    form.save()
    return HttpResponseRedirect(reverse('course-specialist-list'))
  return render(request, 'webpage/coursespecialist_form.html', {'form': form}) 

# delete course specialist
def course_specialist_delete(request, pk):
  query = CourseSpecialist.objects.get(pk=pk)
  query.delete()
  return HttpResponseRedirect(reverse('course-specialist-list'))

# course specialist list
class CourseSpecialistListView(generic.ListView):
  model = CourseSpecialist

# course specialist detail
class CourseSpecialistDetail(generic.DetailView):
  model = CourseSpecialist
  template_name ='webpage/coursespecialist_detail.html'

# course list
class CourseListView(generic.ListView):
  model = Course

# course detail
class CourseDetail(generic.DetailView):
  model = Course
  template_name ='webpage/course_detail.html'

# update course
def course_update(request, pk): 
  instance = get_object_or_404(Course, pk=pk)
  form = CourseForm(request.POST or None, instance=instance)
  if form.is_valid():
    form.save()
    return HttpResponseRedirect(reverse('course-list'))
  return render(request, 'webpage/course_form.html', {'form': form}) 

# course delete
def course_delete(request, pk):
  query = Course.objects.filter(pk=pk)
  query.delete()
  return HttpResponseRedirect(reverse('course-list'))

# create account
def create_account(request):
  if request.method == 'POST':
    form = UserForm(request.POST, request.FILES)
    if form.is_valid():
      user = User()
      user.username = form.cleaned_data['username']
      user.email = form.cleaned_data['email']
      user.set_password(form.cleaned_data['password'])
      user.save()
      return HttpResponseRedirect(reverse('home-page'))

  else:
    form = UserForm()

  context = {
    'form': form,
  }

  return render(request, 'webpage/user_form.html', context)

# registe student
class RegisterStudentCreate(LoginRequiredMixin, CreateView):
  model = RegisterStudent
  fields = ['name', 'course', 'start_date']
  def get_initial(self, **kwargs):
    print(len(self.kwargs))
    if len(self.kwargs) > 0:
      initial = super().get_initial()
      name = self.request.user
      course = Course.objects.get(pk=self.kwargs["pk"])
      initial['course'] = course
      initial['name'] = name
      return initial
    else:
      initial = super().get_initial()
      name = self.request.user
      initial['name'] = name
      return initial
  success_url = reverse_lazy('home-page')

# course post list
def course_post_list(request, pk):
  course_query = get_object_or_404(Course, pk=pk)
  context = {
    'course': course_query,
  }

  return render(request, 'webpage/coursepost_list.html', context=context)

# specialist post create
def specialist_post_create(request, pk):
  course = Course.objects.get(pk = pk)
  if request.method == 'POST':
    form = AdminPostForm(request.POST, request.FILES)
    if form.is_valid():
      specialist_post = Post()
      specialist_post.content = form.cleaned_data['content']
      specialist_post.photo = form.cleaned_data['photo']
      specialist_post.course = Course.objects.get(pk = pk)
      specialist_post.post_creator = course.course_specialist
      specialist_post.save()

      return HttpResponseRedirect(reverse('course-post-list', kwargs={'pk': pk}))

  else:
    form = AdminPostForm()

  context = {
    'form': form,
    'course': course,
  }

  return render(request, 'webpage/adminpost_form.html', context)

# create course question
def course_question_create(request, pk):
  course = Course.objects.get(id = pk)
  if request.method == 'POST':
    form = CourseQuestionForm(request.POST, request.FILES)
    if form.is_valid():
      course_qus = CourseQuestion()
      course_qus.student = RegisterStudent.objects.get(name = request.user, course_id = pk)
      course_qus.course = Course.objects.get(pk = pk)
      course_qus.question = form.cleaned_data['question']
      course_qus.is_answered = False
      course_qus.save()

      return HttpResponseRedirect(reverse('course-post-list', kwargs={'pk': pk}))

  else:
    form = CourseQuestionForm()

  context = {
    'form': form,
    'course': course,
  }

  return render(request, 'webpage/coursequestion_form.html', context)

# course question delete
def question_delete(request, course_id, qus_id):
  query = CourseQuestion.objects.get(pk=qus_id)
  query.delete()
  return HttpResponseRedirect(reverse('course-post-list', kwargs={'pk': course_id}))

# answer question
def question_answer(request, course_id, qus_id):
  CourseQuestion.objects.filter(pk=qus_id).update(is_answered=1)
  return HttpResponseRedirect(reverse('course-post-list', kwargs={'pk': course_id}))


# course delete by student
def course_delete_by_student(request, student_id, course_id):
  qus = CourseQuestion.objects.filter(student=student_id, course=course_id)
  qus.delete()
  student = RegisterStudent.objects.filter(pk=student_id, course=course_id)
  student.delete()
  return HttpResponseRedirect(reverse('home-page'))

webpage/templates/webpage/adminpost_form.html
{% extends "base_generic.html" %}

{% block content %}
  <br/>
  {% if course %}
    <h3>Post for {{course.name}}</h3><hr><br/>
  {% endif %}
  {% if user.is_superuser == 1 %}
    <h1>Admin Create Post Form</h1><hr>
  {% endif %}
  <form action="" method="post" enctype="multipart/form-data">
      {% csrf_token %}
      <table>
      {{ form.as_table }}
      </table>
      <input type="submit" value="Submit" />
  </form>
{% endblock %}

webpage/templates/webpage/course_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>{{course.name}}</h1><hr><br/>
  {% if course.course_specialist.id != Null %}
    <p><img src="{{ course.course_specialist.photo.url }}" width="30" height="30"/>
      <a href="{% url 'course-specialist-detail' course.course_specialist.id %}">{{course.course_specialist}}</a>
    </p><br/>
  {% endif %}
  <img src="{{ course.photo.url }}" width="300" height="200"/><br/><br/>
  <p>{{course.description}}</p><br/><br/>

  {% if not user.is_authenticated %}
    <p><a href="{% url 'register-with-course' course.id %}">Register</a></p>
  {% endif %}
  <!-- {% if user.is_authenticated and user.is_superuser == 0 %}
    <a href="{% url 'home-page' %}">Back</a>
  {% else %}
    <a href="{% url 'course-list' %}">Back</a>
  {% endif %} -->
{% endblock %}

webpage/templates/webpage/course_form.html
{% extends "base_generic.html" %}

{% block content %}
  <br/>
  <h3>Course Form</h3><hr>
  <form action="" method="post" enctype="multipart/form-data">
      {% csrf_token %}
      <table>
      {{ form.as_table }}
      </table>
      <input type="submit" value="Submit" />
  </form>
{% endblock %}

webpage/templates/webpage/course_list.html
{% extends "base_generic.html" %}

{% block content %}
  <br/>
  <h1>All Courses</h1><hr>

  {% if course_list %}
    <table class="table table-striped table-sm ">
      <tr>
        <th>Course</th>
        <th>Course Specialist</th>
        <th></th>
        <th></th>
      </tr>
      {% for course in course_list %}
        <tr>
          <td>
            <img src="{{ course.photo.url }}" width="30" height="30"/>
            <a href="{% url 'course-detail' course.pk %}">
              {{ course.name }}
            </a>
          </td>
          <td>
            {% if course.course_specialist != Null %}
              <img src="{{ course.course_specialist.photo.url }}" width="30" height="30"/> 
              {{ course.course_specialist.name }}
            {% endif %}
          </td>
            {% if user.is_authenticated %}
              {% if user.is_superuser == 1 %}
                <td>
                  <a href="{% url 'course-update' course.pk %}">update</a>
                </td>
                <td>
                  <a href="{% url 'course-delete' course.pk %}">delete</a>
                </td>
              {% endif %}
            {% else %}
              <td>
                <a href="{% url 'register-with-course' course.pk %}">Register</a>
              <td>
            {% endif %}
        </tr>
      {% endfor %}
    </table>
  {% else %}
    <p>There are no course speciaslits.</p>
  {% endif %}  
  <a href="{% url 'home-page' %}">Back</a>  
  {% if user.is_superuser == 1 %}
    | <a href="{% url 'course-create' %}">Create Course</a>
  {% endif %}     
{% endblock %}

webpage/templates/webpage/coursepost_list.html
{% extends "base_generic.html" %}

{% block content %}
  <div class="container-fluid" style="padding-top: 10px;">
    <div class="row">
      <div class="col-sm-9">
        <h3>{{ course.name }} Course</h3><hr>
        {% if user == course.course_specialist.name %}
          <a href="{% url 'specialist-post-create' course.pk %}">{{ course.name }} Post Create</a> |
        {% else %}
          {% if course.post_set.count > 1 %}
            <a href="{% url 'course-question-create' course.pk %}">Create Question</a> |
          {% endif %}
        {% endif %}
        <a href="{% url 'home-page' %}">Course List</a> <br/><br/>
        {% if user.is_superuser == 0 %}
          {% for post in course.post_set.all %}
            {% if post.post_creator.name.is_superuser == 0 %}
              <img src="{{ post.course.course_specialist.photo.url }}" width="30" height="30"/>
              <span style="padding-right:50px; font-weight:bold; font-size:20px;">{{ post.course.course_specialist.name }}</span>
              <span style="font-size:12px;">{{post.post_date}}</span><br/>
              <p style="word-wrap: break-word; padding-left: 35px;">{{ post.content }}</p>
              <span style="padding-left: 35px;"><img src="{{ post.photo.url }}" width="300" height="200"/></span>
              {% if user == post.course.course_specialist.name %}
                <a href="{% url 'post-update' post.pk %}">Update</a> |
                <a href="{% url 'post-delete' post.pk %}">Delete</a>
              {% endif %}
              <br/><br/>
            {% endif %}
          {% endfor %}
        {% endif %}
      </div>
      <div class="col-sm-3" style="padding-top: 10px;">
        {% if course.coursequestion_set.count > 0 %}
          <b>Course's Questions</b><hr>
          {% for qus in course.coursequestion_set.all %}
            <b>{{ qus.student.name }} :</b>
            <span style="width: 200px; word-wrap: break-word;">{{ qus }}</span>
            {% if user == qus.student.name %}
              <a href="{% url 'qus-delete' qus_id=qus.id course_id=course.id %}">Del</a>
            {% endif %}
            {% if qus.is_answered == 1 %}
              <span style="font-size: 5px; color: green;">
                <b>answered</b>
              </span>
            {% else %}
              <span style="font-size: 5px; color: red;">
                <b>no-answered</b>
                {% if course.course_specialist.name == request.user %}
                  <a href="{% url 'qus-answer' qus_id=qus.id course_id=course.id %}">Answer</a>
                {% endif %}
              </span>
            {% endif %}
            <br/>
          {% endfor %}
        {% endif %}
      </div>
    </div>
  </div>

  {% load static %}

{% endblock %}

webpage/templates/webpage/coursequestion_form.html
{% extends "base_generic.html" %}

{% block content %}
  <br/>
  <b>Question for {{ course.name }}</b><br/><br/>
  <form action="" method="post" enctype="multipart/form-data">
      {% csrf_token %}
      <table>
      {{ form.as_table }}
      </table>
      <input type="submit" value="Submit" />
  </form>
{% endblock %}

webpage/templates/webpage/coursespecialist_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>{{coursespecialist.name}}</h1><hr><br/>

  <img src="{{ coursespecialist.photo.url }}" width="300" height="200"/><br/><br/>
  <p>{{coursespecialist.bio}}</p><br/>
  <h4>Specialist's Courses</h4><hr>
  {% for course in coursespecialist.course_set.all %}
    <img src="{{ course.photo.url }}" width="30" height="30"/>
    <a href="{% url 'course-detail' course.pk %}">{{course.name}}</a>
    <br/><br/>
  {% endfor %}
  <hr>
  <br/>
  <!-- {% if user.is_authenticated and user.is_superuser == 0 %}
    <a href="{% url 'home-page' %}">Back</a>
  {% else %}
    <a href="{{ request.META.HTTP_REFERER }}" >Back</a>
  {% endif %} -->
{% endblock %}

webpage/templates/webpage/coursespecialist_form.html
{% extends "base_generic.html" %}

{% block content %}
  <br/>
  <h3>Course Specialist Form</h3><hr>
  <form action="" method="post" enctype="multipart/form-data">
      {% csrf_token %}
      <table>
      {{ form.as_table }}
      </table>
      <input type="submit" value="Submit" />
  </form>
{% endblock %}

webpage/templates/webpage/home_page.html
{% extends "base_generic.html" %}

{% block title %}<title>Online Class Page</title>{% endblock %}

{% block content %}
  <br/>
  {% if user.is_authenticated %}
    {% if user.is_superuser == 1 %}
      <h1>Adminstrator Page</h1><hr>
      <p><a href="{% url 'admin-post-create' %}">Create Post </a> |
        <a href="{% url 'course-specialist-list' %}">Course Specialist List </a> |
        <a href="{% url 'course-list' %}">Course List </a>
      </p>
      {% for post in course_specialist.post_set.all %}
        <img src="{{ course_specialist.photo.url }}" width="30" height="30"/>
        <span style="padding-right:50px; font-weight:bold; font-size:20px;">{{ course_specialist.name }}</span>
        <span style="font-size:12px;">{{post.post_date}}</span><br/>
        <p style="padding-left:35px;">{{ post.content }}</p>
        <p style="padding-left:35px;"><img src="{{ post.photo.url }}" width="300" height="150"/></p>
        {% if user == course_specialist.name %}
          <span style="padding-left:35px;">
            <a href="{% url 'post-update' post.pk %}">Update</a> |
            <a href="{% url 'post-delete' post.pk %}">Delete</a>
          </span>
        {% endif %}
        <br/><br/>
      {% endfor %}
    {% else %}
      {% if user == course_specialist.name %}
        <h1>Course Specialist {{ course_specialist.name }} Page</h1><hr><br/>
        <h3>Course List</h3>
        <br/>
        <table class="table table-striped table-sm ">
          <tr>
            <th>Course</th>
            <th>Student Count</th>
            <th></th>
          </tr>
          {% for course in course_specialist.course_set.all %}
          <tr>
            <td>
              <img src="{{ course.photo.url }}" width="30" height="30"/>
              <a href="{% url 'course-post-list' course.id %}">{{ course.name }}</a>
            </td>
            <td>
              <span style="padding-left: 30px;">{{ course.registerstudent_set.count }}
            </td>
          </tr>
          {% endfor %}
        </table>
      {% else %}
        <h1>Student {{ user.get_username }} Page</h1><hr><br/>
        <h3>Course List</h3>
        <br/>
        <table class="table table-striped table-sm ">
          <tr>
            <th>Course</th>
            <th>Course Specialist</th>
            <th></th>
          </tr>
          {% for student in students %}
            <tr>
              <td>
                <img src="{{ student.course.photo.url }}" width="30" height="30"/>
                <a href="{% url 'course-post-list' student.course.id %}">{{ student.course.name }}</a>
              </td>
              <td>
                {% if student.course.course_specialist.id != Null %}
                  <span style="padding-left: 20px;">
                    <img src="{{ student.course.course_specialist.photo.url }}" width="30" height="30"/> 
                    <a href="{% url 'course-specialist-detail' student.course.course_specialist.id %}">{{ student.course.course_specialist }}</a>
                  </span>
                {% endif %}
              </td>
              <td>
                <a href="{% url 'course-delete-by-student' student_id=student.id course_id=student.course.id %}">delete</a>
              </td>
            </tr>
          {% endfor %}
        </table>
      {% endif %}
    {% endif %}
  {% else %}
    <h1>Welcome from IT online class</h1><hr><br>
    <a href="{% url 'create-account' %}">Create Account</a> | 
    <a href="{% url 'course-specialist-list' %}">Course Specialist List</a> | 
    <a href="{% url 'course-list' %}">Course List</a>
    <br><br>

    {% for post in course_specialist.post_set.all %}
      <img src="{{ course_specialist.photo.url }}" width="30" height="30"/>
      <span style="padding-right:50px; font-weight:bold; font-size:20px;">{{ course_specialist.name }}</span>
      <span style="font-size:12px;">{{post.post_date}}</span><br/>
      <p style="padding-left:35px;">{{ post.content }}</p>
      <p style="padding-left:35px;"><img src="{{ post.photo.url }}" width="300" height="150"/></p>
      <p style="padding-left:35px;"><a href="{% url 'register-with-course' post.course_id %}">Register</a></p>
    {% endfor %}
  {% endif %}

  {% load static %}

{% endblock %}

webpage/templates/webpage/post_form.html
{% extends "base_generic.html" %}

{% block content %}
  <br/>
  <h3>Post Create Form</h3><hr>
  <form action="" method="post" enctype="multipart/form-data">
      {% csrf_token %}
      <table>
      {{ form.as_table }}
      </table>
      <input type="submit" value="Submit" />
  </form>
{% endblock %}